name: Check Deprecated Actions

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check-deprecated-actions:
    name: Check for Deprecated Actions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Check for deprecated actions/cache versions
        run: |
          echo "=== Checking for deprecated actions/cache versions ==="
          
          # Check all workflow files for references to actions/cache v2 or v3
          echo "Checking workflow files..."
          find .github/workflows -name "*.yml" -o -name "*.yaml" | while read -r file; do
            echo "Checking file: $file"
            # Skip the current check file to avoid self-matching
            if [[ "$file" == ".github/workflows/check-deprecated-actions.yml" ]]; then
              echo "Skipping self-check for $file"
              continue
            fi
            if grep -q "uses:.*actions/cache@v[23]" "$file"; then
              echo "❌ ERROR: Found deprecated actions/cache version in $file"
              grep -n "uses:.*actions/cache@v[23]" "$file"
              exit 1
            else
              echo "✅ No deprecated actions/cache versions found in $file"
            fi
          done
          
          echo "=== Checking for other potentially deprecated actions ==="
          
          # Check for other common deprecated actions
          deprecated_actions=(
            "uses:.*actions/setup-node@v[1-3]"
            "uses:.*actions/setup-python@v[1-3]"
            "uses:.*actions/setup-go@v[1-3]"
            "uses:.*actions/checkout@v[1-3]"
          )
          
          for action_pattern in "${deprecated_actions[@]}"; do
            echo "Checking for pattern: $action_pattern"
            find .github/workflows -name "*.yml" -o -name "*.yaml" | while read -r file; do
              # Skip the current check file to avoid self-matching
              if [[ "$file" == ".github/workflows/check-deprecated-actions.yml" ]]; then
                continue
              fi
              if grep -q "$action_pattern" "$file"; then
                echo "⚠️ WARNING: Found potentially deprecated action in $file"
                grep -n "$action_pattern" "$file"
              fi
            done
          done
          
          echo "=== Action version check complete ==="
          
      - name: Check for composite actions that might use deprecated actions
        run: |
          echo "=== Checking for composite actions that might use deprecated actions ==="
          
          # This is a more advanced check that would require parsing composite actions
          # For now, we'll just list any composite actions being used
          echo "Checking for composite actions..."
          find .github/workflows -name "*.yml" -o -name "*.yaml" | while read -r file; do
            # Skip the current check file to avoid self-matching
            if [[ "$file" == ".github/workflows/check-deprecated-actions.yml" ]]; then
              continue
            fi
            echo "Checking file: $file"
            # Look for uses of local composite actions
            if grep -q "uses: \./" "$file"; then
              echo "Found local composite action usage in $file:"
              grep -n "uses: \./" "$file"
            fi
          done
          
          echo "=== Composite action check complete ==="