on:
  pull_request:
    branches: [ master ]
name: Benchmarks
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            target
            ~/.cargo/git
            ~/.cargo/registry
          key: ${{ runner.os }}-cargo-v4-${{ hashFiles('**/Cargo.lock') }}
      - uses: smrpn/criterion-compare-action@move_to_actions 
        with:
          cwd: benches
          token: ${{ secrets.GITHUB_TOKEN }}

