on:
  pull_request_target:
    branches: [ master ]
name: Benchmarks
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Debug Action Versions
        run: |
          echo "=== Checking for potential deprecated action usage ==="
          echo "Current runner version: '${{ runner.version }}'"
          echo "Checking for any references to actions/cache v2 or v3..."
          echo "This is a preventative debug step to identify any deprecated action usage."
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Cache cargo
        id: cache-cargo
        uses: actions/cache@v4
        with:
          path: |
            target
            ~/.cargo/git
            ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Log cache info for cargo
        run: |
          echo "Cache hit for cargo: ${{ steps.cache-cargo.outputs.cache-hit }}"
          echo "Cache key for cargo: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
      - uses: boa-dev/criterion-compare-action@v3.2.4
        with:
          cwd: benches
          # Compare against the branch the PR targets (default) if desired
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

