on:
  pull_request_target:
    branches: [ master ]
name: Benchmarks
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Debug Action Versions
        run: |
          echo "=== Checking for potential deprecated action usage ==="
          echo "Current runner version: '${{ runner.version }}'"
          echo "Checking for any references to actions/cache v2 or v3..."
          echo "This is a preventative debug step to identify any deprecated action usage."
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Cache cargo
        id: cache-cargo
        uses: actions/cache@v4
        with:
          path: |
            target
            ~/.cargo/git
            ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Log cache info for cargo
        run: |
          echo "Cache hit for cargo: ${{ steps.cache-cargo.outputs.cache-hit }}"
          echo "Cache key for cargo: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
      - name: Install cargo-criterion
        run: cargo install cargo-criterion
      - name: Run benchmark
        run: |
          cd benches
          cargo criterion --plotting-backend plotters --output-format html

